Add API to WiFi class to configure wdog feed function
arduino/ArduinoCore-mbed pull request #258
Opened 2021-06-10 20:52 UTC by pennam

This pr add the possibility to configure the watchdog feed function through API in the WiFi class and trigger the watchdog during download process.

2021-06-11 06:31 UTC, aentinger requested changes

2021-06-11 06:31 UTC, aentinger commented on libraries/WiFi/src/WiFi.h
> +#define WIFI_HAS_FEED_WATCHDOG_FUNC
Please use a more unique name, e.g. `ARDUINO_PORTENTA_H7_WIFI_HAS_FEED_WATCHDOG_FUNC`

2021-06-11 06:31 UTC, aentinger commented on libraries/WiFi/src/WiFi.h
>  typedef void* (*voidPrtFuncPtr)(void);
```C++
typedef void(*ArduinoPortentaH7WiFiFeedWatchdogFuncPtr)(void);
```
also
```diff
-typedef void* (*voidPrtFuncPtr)(void);
+typedef void (*voidPrtFuncPtr)(void);
```

2021-06-11 12:23 UTC, pennam commented on libraries/WiFi/src/WiFi.h
> +#define WIFI_HAS_FEED_WATCHDOG_FUNC
fixed with https://github.com/arduino/ArduinoCore-mbed/pull/258/commits/28bae3e014097cf9621fc911a795c10a922e2ba7

2021-06-15 04:39 UTC, aentinger approved these changes
Tested - works :heavy_check_mark:

2021-06-15 04:39 UTC, merged