Enable 320x320 resolution for himax HM01B0
arduino/ArduinoCore-mbed pull request #294
Opened 2021-07-25 20:47 UTC by idohalamit

I did that the same way OpenMV did:
github.com/openmv/openmv/blob/master/src/omv/sensors/hm01b0.c

 - Added constants consistently with QVGA and QQVGA modes.

 - Updated himax.cpp, camera.cpp accordingly.

My first commit to an open source project <3

2021-07-25 20:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/ArduinoCore-mbed?pullRequest=294) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/ArduinoCore-mbed?pullRequest=294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/ArduinoCore-mbed?pullRequest=294) it.</sub>

2021-07-26 07:46 UTC, facchinm commented
Hi @idohalamit , thanks for your submission! I'm reviewing the code and there are a bunch of small things that need fixing but overall it's good! I'm commenting the needed changes inline, let me know if they sound ok to you  :wink:

2021-07-26 07:50 UTC, facchinm requested changes

2021-07-26 07:50 UTC, facchinm commented on libraries/Portenta_Camera/camera.cpp
> +  if (resolution > CAMERA_RMAX) {
No need to do this if we add a `CAMERA_R320x320` entry to the enum

2021-07-26 07:50 UTC, facchinm commented on libraries/Portenta_Camera/camera.h
> +    CAMERA_RMAX     = 0x02    /* 320x320 Resolution */
Let's add a `CAMERA_R320x320` mode and keep `CAMERA_RMAX` without any attached value, since it's used in a  "last element of the enum" fashion.

2021-07-26 12:12 UTC, idohalamit commented on libraries/Portenta_Camera/camera.h
> +    CAMERA_RMAX     = 0x02    /* 320x320 Resolution */
Looks good!

2021-07-26 12:28 UTC, facchinm commented on libraries/Portenta_Camera/camera.h
> +    CAMERA_RMAX     = 0x02    /* 320x320 Resolution */
Not really what I meant :slightly_smiling_face: 
What I'm asking for is something like 
```
enum {
    CAMERA_R160x120 = 0x00,   /* QQVGA Resolution */
    CAMERA_R320x240 = 0x01,   /* QVGA Resolution  */
    CAMERA_R320x320 = 0x02,   /* 320x320 Resolution */
    CAMERA_RMAX
}
```
then, use the `CAMERA_R320x320` as reference.

2021-07-27 15:51 UTC, sebromero commented on libraries/Portenta_Camera/camera.h
> +    CAMERA_RMAX     = 0x02    /* 320x320 Resolution */
```suggestion
    CAMERA_R320x320     = 0x02,    /* 320x320 Resolution */
    CAMERA_RMAX
```

2021-08-13 13:07 UTC, idohalamit commented
Should I commit anything more?

2021-08-13 13:09 UTC, sebromero commented
@idohalamit I think we're good. @facchinm If you agree I suggest we merge 🚢

2021-08-13 13:10 UTC, sebromero approved these changes
LGTM

2021-08-15 18:13 UTC, idohalamit commented
I do!
I had some trouble with the serial connection in the [demo,](https://docs.arduino.cc/tutorials/portenta-vision-shield/vs-ard-gs) I did some workaround.
They should work even though I can't test them right now.
Also, you'd probably want to change the hard-coded serial port.
[LiveFeed320x320.ino.txt](https://github.com/arduino/ArduinoCore-mbed/files/6988619/LiveFeed320x320.ino.txt)
[CameraViewer320x320.pde.txt](https://github.com/arduino/ArduinoCore-mbed/files/6988622/CameraViewer320x320.pde.txt)

2021-08-16 08:57 UTC, merged

2021-08-16 08:58 UTC, facchinm commented
Merged, thanks a lot for your contribution :slightly_smiling_face: !

2021-08-16 09:09 UTC, sebromero commented
@idohalamit Thanks. Yes, the example sketch for this has some issues on Windows. I haven't gotten around to investigate as I don't have a Windows computer. Do you have an idea what exactly gets messed up in regards to the serial connection?

2021-08-20 12:37 UTC, idohalamit commented
I haven't isolated the problem, but sending the data in small chunks (I used 512 bytes), using Serial.flush() and adding delays between sends fixes it.