Call objcopy.postobjcopy only when needed
arduino/ArduinoCore-mbed pull request #524
Opened 2022-07-20 11:22 UTC by facchinm

2022-07-20 14:38 UTC, cmaglie approved these changes

2022-07-20 16:25 UTC, rsora requested changes
@facchinm @pennam 
What about this line?
https://github.com/arduino/ArduinoCore-mbed/pull/524/files#diff-c3a7c63d53cdec402cf559c1707ce5ef639a7e59e575f41ac5c8f5941e806a9fL265

```
portenta_x8.build.postbuild.cmd="{tools.imgtool.path}/{tools.imgtool.cmd}" exit
```

do we need to remove this too?

2022-07-21 09:44 UTC, facchinm commented
> @facchinm @pennam What about this line? https://github.com/arduino/ArduinoCore-mbed/pull/524/files#diff-c3a7c63d53cdec402cf559c1707ce5ef639a7e59e575f41ac5c8f5941e806a9fL265
> 
> ```
> portenta_x8.build.postbuild.cmd="{tools.imgtool.path}/{tools.imgtool.cmd}" exit
> ```
> 
> do we need to remove this too?

Great catch, fixing and pushing back

2022-07-21 09:53 UTC, rsora approved these changes
Tests on the Web Editor environment are good!
:shipit:

2022-07-21 12:05 UTC, merged