Use consistent naming for Serial interfaces
arduino/ArduinoCore-mbed pull request #54
Opened 2020-09-12 09:17 UTC by sbhklr

After a discussion with @hpssjellis I concluded that it's confusing the map the serial interfaces to different UART port depending on the core. It's probably more understandable if the M4 doesn't support `Serial` for now, or to map it also to _UART1_. In the future we can add support for `Serial` to the M4 by piping the messages to the M7.

2020-09-12 09:45 UTC, per1234 commented
@sbhklr if the "Compile Examples" CI workflow needs to be adjusted to not compile the `/libraries/Scheduler/examples/MultipleBlinks` example sketch for the Portenta (M4 core) board, I'm happy to assist with that.

2020-09-12 09:46 UTC, sbhklr commented
> @sbhklr if the "Compile Examples" CI workflow needs to be adjusted to not compile the `/libraries/Scheduler/examples/MultipleBlinks` example sketch for the Portenta (M4 core) board, I'm happy to assist with that.

Thanks Per! No, I think it should absolutely be compiled, but I forgot to adjust the example. Will do now :-)

2020-09-12 10:18 UTC, sbhklr commented
@per1234 Hmm, I was thinking of remapping the Serial for the M4 in the examples using 
```
#ifdef CORE_CM4
  #define Serial Serial1
#endif
```
or 
```
#ifdef CORE_CM4
  #define Serial _UART1_
#endif
```
It pollutes the examples a bit though. Not sure if it's the best approach. How would you go about it?

2020-09-12 11:14 UTC, per1234 commented
That is a good consideration!

We are using this sketch for two purposes:
- Demonstrate the library to the user
- Test the compilation of the library

Only considering the first, I would say that it's best to:
- Leave the sketch as it was, without the preprocessor "pollution"
- Clearly document the names of the serial interfaces in the Arduino reference in the table here: https://www.arduino.cc/reference/en/language/functions/communication/serial/

and leave it up to the user to adjust the example to Serial1 when they want to use it on the Portenta (M4 core) board.

However, this will require us to configure the CI workflow to not compile the sketch, meaning we lose that basic check on compatibility of the Scheduler library with the Portenta (M4 Core) board.

A workaround for that could be to add a sketch only intended to be used for testing to a dedicated location in the Arduino mbed OS-enabled platforms platform, something like `test/sketches/libraries/Scheduler/Scheduler.ino`, then configure the CI workflow to compile the test sketch for all boards and the user example only for the boards its expected to compile for. That test sketch can be as user-unfriendly as we like because it's never intended to be seen by the standard users. It can also be more targeted on excercising only the API of the Scheduler library, rather than needing to contain code unrelated to make it actually do something useful.

I think something like this was done in the ArduinoIoTCloud library:
https://github.com/arduino-libraries/ArduinoIoTCloud/tree/master/examples/utility/ArduinoIoTCloud_Travis_CI

---
As for the examples in the `Portenta_System` library, I'm not concerned about a little preprocessor "pollution" there because those examples are targeted to more advanced users who won't get confused by the preprocessor stuff. I actually don't even know enough about Portenta to understand whether those examples are relevant to the M4 core board.

2020-09-13 08:34 UTC, per1234 commented
Due to the long standing precedent [set by other Arduino boards](https://www.arduino.cc/reference/en/language/functions/communication/serial/), I think it would be confusing for `Serial` and `Serial1` to be names for the same interface.

I actually prefer for users to be required to adjust the sketch to use Serial1 instead of Serial because this will make it clear to them that they shouldn't expect the code to use the CDC serial port, but rather pins 13/14 just as it would on the Portenta (M7 core) or MKR boards, and similar to any other Arduino board.

Consider Sebastian's suggestion from eariler:
>In the future we can add support for Serial to the M4 by piping the messages to the M7.

It would be confusing for the meaning of `Serial` to change once more when that happens.

2020-09-13 15:43 UTC, hpssjellis commented
@per1234 and @sbhklr 

_In the future we can add support for Serial to the M4 by piping the messages to the M7._ 

That makes a lot of sense. I can do my way with a ```#define Serial Serial1``` statement. 

The piping will probably use RPC which for me does not work unless I change my library cflags.txt and cxxflags.txt files with ```-fexceptions``` added to the bottom of the files. Is that something you want to make default to the library? I placed an issue [here](https://github.com/arduino/ArduinoCore-mbed/issues/55)

2020-09-25 10:46 UTC, sbhklr commented
@per1234 We're gonna merge this PR and in a second step figure out a mechanism for mapping Serial on the M4. How do you suggest to proceed with the examples for CI? I like the `test` folder approach that you mentioned. This would eventually allow us to do some sort of unit/integration testing.

2020-09-25 12:07 UTC, per1234 commented
>We're gonna merge this PR and in a second step figure out a mechanism for mapping Serial on the M4.

I think that's the best approach.

>How do you suggest to proceed with the examples for CI?

I would make a sketch that uses the full API of the Scheduler library, and nothing else. Something like this:
```c++
#include <Scheduler.h>

void setup() {
  Scheduler.startLoop(startLoopTask1);
  Scheduler.startLoop(startLoopTask2, 123);
  Scheduler.start(startTask1);
  Scheduler.start(startTask2, 123);
  Scheduler.start(startParametricTask1, (void*)"asdf");
  Scheduler.start(startParametricTask2, (void*)"zxcv", 123);
  Scheduler.yield();
}

void loop() {}
void startLoopTask1() {}
void startLoopTask2() {}
void startTask1() {}
void startTask2() {}
void startParametricTask1(void *bar) {}
void startParametricTask2(void *bar) {}
```
Put it in the dedicated folder for test sketches and then configure the "Compile Examples" workflow to compile it for all three boards.

2020-09-25 16:25 UTC, per1234 commented
@sbhklr I would like to see the following added to this PR:
- Add [your preprocessor code](https://github.com/arduino/ArduinoCore-mbed/pull/54#issuecomment-691463198) to the `Portenta_System` library's examples to make them still compile for the Portenta H7 (M4 core) board.
- Update "Compile Examples" workflow so the Scheduler library examples are not compiled for the Portenta H7 (M4 core) board. This only requires moving the "`libraries/Scheduler`" path from [here](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L27) to [there](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L42) and [there](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L48)

2020-09-25 16:26 UTC, per1234 requested changes
I would like to see the following added to this PR:
- Add [your preprocessor code](https://github.com/arduino/ArduinoCore-mbed/pull/54#issuecomment-691463198) to the `Portenta_System` library's examples to make them still compile for the Portenta H7 (M4 core) board.
- Update "Compile Examples" workflow so the Scheduler library examples are not compiled for the Portenta H7 (M4 core) board. This only requires moving the "`libraries/Scheduler`" path from [here](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L27) to [there](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L42) and [there](https://github.com/arduino/ArduinoCore-mbed/blob/6511709a369133d05a05ff28013b5e11b2cb3a95/.github/workflows/compile-examples.yml#L48)

2020-10-12 10:19 UTC, sbhklr commented
@per1234 Github doesn't allow me to re-request a review from you, so I'm just gonna tag you here :-) Can you have a look at the changes? I'd love to get this into the imminent release of 1.2.3

2020-10-12 10:26 UTC, per1234 approved these changes
I like this change. Thanks @sbhklr for making it and also to @hpssjellis for the suggestion!

2020-10-27 14:48 UTC, facchinm commented
Replaced by 58fee8b . 
96a3416 will be merged standalone

2020-10-27 14:48 UTC, closed without merging

2020-10-27 21:38 UTC, sbhklr commented
@facchinm no need to apply https://github.com/arduino/ArduinoCore-mbed/commit/96a3416f3fb622ac5d5ad3782d59b9c1ca49646e as this is redundant with your changes from https://github.com/arduino/ArduinoCore-mbed/commit/58fee8b295474eee80e7b974096d6e8c7ffc0c41