Provide CAN library for enabling useage of CAN for ArduinoCore-mbed enabled boards.
arduino/ArduinoCore-mbed pull request #633
Opened 2023-03-06 12:21 UTC by aentinger

**Caveat**: which also make CAN available on their GPIOs.

Requires: https://github.com/arduino/ArduinoCore-API/pull/185 .

2023-04-26 10:35 UTC, facchinm requested changes

2023-04-26 10:35 UTC, facchinm commented on variants/PORTENTA_H7_M7/pins_arduino.h
> +#define PIN_CAN1_TX       (PH_13)
On Portenta we only expose one CAN bus in the HD connectors, we should probably expose only that one to the user (PH13/PB8)
![2023-04-26-123445_922x44_scrot](https://user-images.githubusercontent.com/8843437/234549928-7f0db582-09f8-4ae2-8bb9-ffc193585f77.png)

2023-05-02 11:23 UTC, aentinger commented on variants/PORTENTA_H7_M7/pins_arduino.h
> +#define PIN_CAN1_TX       (PH_13)
Sorry, I must have overlooked the notification for your comment. I've fixed this in f4cad9f119ed6a18cd8211fecac254347debcde0 .

**Note**: I'm not really happy about the divergence between software object (CAN) and labeling on the high-density connector (CAN1) but if we follow the usual Arduino policy of enumerating software objects by amount of available peripherals (i.e. the first CAN peripheral is mapped to CAN, the second CAN peripheral maps to CAN1, etc.) then in this case mapping the bus labelled CAN1 to a software object called CAN is only a logical (if unfortunate) choice.

What are your thoughts on this?

2023-05-02 12:53 UTC, facchinm approved these changes

2023-05-02 12:54 UTC, merged

2023-05-02 18:46 UTC, aentinger commented on variants/PORTENTA_H7_M7/pins_arduino.h
> +#define PIN_CAN1_TX       (PH_13)
Alright, good for me :wink: . I've noted this discrepancy in the comments, at least that should help if/when someone falls over this.