Make WiFiClientSSL class available
arduino/ArduinoCore-mbed pull request #647
Opened 2023-03-23 08:52 UTC by karlsoderby

`WiFiSSLClient` was missing in `WiFi.h`, so examples using SSL fails to compile.

The SSL example was tested with the GIGA R1 WiFi board successfully.

2023-04-06 12:13 UTC, sebromero approved these changes
LGTM

2023-04-06 12:14 UTC, sebromero commented
@karlsoderby Where is the example sketch that you're referring to?

2023-04-26 10:30 UTC, facchinm requested changes
Take into account the flash occupation increase

2023-05-19 15:28 UTC, sebromero commented
@karlsoderby Can you please point me to the examples that were not compiling?

2023-08-09 10:12 UTC, manchoz commented
Hi,
Can't we just include `WiFiSSLClient.h` header in the SSL/TLS examples?

2023-11-28 11:33 UTC, merged