[AE-39] Add API documentation to Camera library
arduino/ArduinoCore-mbed pull request #656
Opened 2023-04-04 14:39 UTC by sebromero

This PR adds the missing documentation to the Camera library. Currently the API documentation is rendered by hand. This process will be automated with a future PR.

2023-04-04 15:47 UTC, alrvid commented on libraries/Camera/docs/README.md
Should the Himax HM01B0 be mentioned too in the list of compatible camera models?

2023-04-04 15:52 UTC, alrvid commented on libraries/Camera/library.properties
Should the fourth camera model be mentioned here too?

2023-04-04 15:54 UTC, alrvid commented on libraries/Camera/src/camera.h
Should the fourth camera model be mentioned?

2023-04-04 15:56 UTC, alrvid commented on libraries/Camera/src/camera.h
Misspelling on line 87.

2023-04-04 16:13 UTC, alrvid commented on libraries/Camera/src/camera.h
The reset() function isn't specifically for getting out of stuck states. What it does differs between the camera models. It does nothing at all on the GC2145. On the OV7670, it reset all configuration registers to the default values. The registers are reset to the defaults on the Himax cameras too, but they also enter Standby Mode, where there is no video output and the power consumption is lowered.

2023-04-04 16:27 UTC, alrvid commented on libraries/Camera/src/camera.h
> +         * @brief Set the sensor in standby mode.
This actually has no effect on none of the currently supported cameras. The Himax cameras can be set in standby mode by calling reset() instead, but not by calling this function.

2023-04-04 16:36 UTC, alrvid requested changes
See the comments for each file.

2023-04-06 16:24 UTC, sebromero commented on libraries/Camera/docs/README.md
Yes

2023-04-07 11:06 UTC, merged