Add support for Arduino Edge Control
arduino/ArduinoCore-mbed pull request #66
Opened 2020-10-05 15:35 UTC by manchoz

Add support for upcoming Arduino Edge Control.

2020-10-05 15:50 UTC, per1234 commented
@manchoz if you want any assistance with enabling CI for the new board, just let me kno.

2020-10-05 15:52 UTC, facchinm requested changes

2020-10-05 15:52 UTC, facchinm commented on mbed-os-to-arduino
> -	| xargs -I{} cp --parent {} "$ARDUINOCOREMBED"/
This one doesn't work as intended in Linux :disappointed: @Polldo proposed to change rewrite this script in python... It may be the right moment. 
Can you remove it from history for now?

2020-10-05 15:52 UTC, facchinm commented on cores/arduino/mbed/components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
> -    virtual bool is_valid_erase(mbed::bd_addr_t addr, mbed::bd_size_t size) const;
This one is a regression, probably a patch was missing during core recompilation

2020-10-05 17:02 UTC, manchoz commented on mbed-os-to-arduino
> -	| xargs -I{} cp --parent {} "$ARDUINOCOREMBED"/
Yes. Dropped from rebase.

2020-10-05 17:03 UTC, manchoz commented on cores/arduino/mbed/components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
> -    virtual bool is_valid_erase(mbed::bd_addr_t addr, mbed::bd_size_t size) const;
Fixed with a few other missing `mbed::` namespaces in companion headers.

2020-10-05 17:04 UTC, manchoz commented
@per1234 yes, please! Thank you!

2020-10-05 18:32 UTC, per1234 commented
@manchoz because the Edge Control board definition specifies M4, I set up the CI to compile the same sketches as for the Portenta H7 (M4 Core) board. There are some compilation errors. I'm not knowledgeable enough on this subject to be able to evaluate which failures are expected and which might represent actual bugs.

Would you mind reviewing these errors in this workflow run log and telling me which of them are expected?:
- https://github.com/per1234/ArduinoCore-mbed/runs/1210718484?check_suite_focus=true#step:7:24
- https://github.com/per1234/ArduinoCore-mbed/runs/1210718484?check_suite_focus=true#step:7:50
- https://github.com/per1234/ArduinoCore-mbed/runs/1210718484?check_suite_focus=true#step:7:57
- https://github.com/per1234/ArduinoCore-mbed/runs/1210718484?check_suite_focus=true#step:7:70
- https://github.com/per1234/ArduinoCore-mbed/runs/1210718484?check_suite_focus=true#step:7:125

Once I know which of the errors are expected, I will configure the workflow to exclude those sketches from being compiled for the Edge Control board.

2021-02-22 12:31 UTC, sebromero commented
@manchoz @facchinm Can we merge this?

2021-02-22 13:04 UTC, sebromero commented
@manchoz @facchinm Can we merge this?

2021-04-06 17:59 UTC, facchinm commented
Rebased and merged as https://github.com/arduino/ArduinoCore-mbed/commit/cbc3305a5d1d04bbeb0d5a8038fbe2b3a3f38197

2021-04-06 17:59 UTC, closed without merging