SocketWrapper - copyable networking clients
arduino/ArduinoCore-mbed pull request #768
Opened 2023-11-21 20:18 UTC by JAndrassy

copyable networking clients

it is done the same way as in other LwIP based Arduino networking libraries including the C33 LwipWrapper. There WiFiClient/EthernetClient is a simple copyable class redirecting every method to the object managing the socket. That object is stored in std:shared_ptr.
The PR uses the existing MbedClient as the managing class and adds the copyable class from which then WiFiClent and EthernetClient inherit.

Right now I can't test WiFi and SSL.

2023-11-22 06:51 UTC, JAndrassy commented
TODO adopt WiFiSSLSE050Client

2023-11-22 07:43 UTC, megacct commented
Great work, I'm back up and running with my telnet server. I did get a crash when doing a client available() or read() (not sure which) after having called a stop() on the client. Easy workaround in my code and probably shouldn't have been doing that anyway.

2024-01-25 10:30 UTC, JAndrassy commented
@facchinm this is important. the networking libraries in this core will not work correctly without this. the copy ability of instanced objects is a feature of the Arduino language. Imagine String would not be copyable in some Core.

2024-01-31 09:58 UTC, pennam commented
@JAndrassy I think you should rebase this on master since `setTimeout` has been renamed in `setSocketTimeout`

2024-01-31 10:23 UTC, JAndrassy commented
@pennam thank you for the reminder. done

2024-01-31 12:13 UTC, pennam requested changes
Thanks for the contribution @JAndrassy 

Do you mind also changing `setEccSlot` visibility? It must be public.

I'm running a bit of testing on this PR so we can hopefully merge it for the next release.

2024-01-31 12:13 UTC, pennam commented on libraries/SE05X/src/WiFiSSLSE050Client.h
> +  void setEccSlot(int KeySlot, const byte cert[], int certLen);
```suggestion

public:
  void setEccSlot(int KeySlot, const byte cert[], int certLen);
```

2024-02-05 08:59 UTC, pennam approved these changes
:+1:  Thanks

2024-02-05 08:59 UTC, merged